/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface PageHome {
    }
    interface SwipeDelete {
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLPageHomeElement extends Components.PageHome, HTMLStencilElement {
    }
    var HTMLPageHomeElement: {
        prototype: HTMLPageHomeElement;
        new (): HTMLPageHomeElement;
    };
    interface HTMLSwipeDeleteElement extends Components.SwipeDelete, HTMLStencilElement {
    }
    var HTMLSwipeDeleteElement: {
        prototype: HTMLSwipeDeleteElement;
        new (): HTMLSwipeDeleteElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "page-home": HTMLPageHomeElement;
        "swipe-delete": HTMLSwipeDeleteElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface PageHome {
    }
    interface SwipeDelete {
        "onDeleted"?: (event: CustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "page-home": PageHome;
        "swipe-delete": SwipeDelete;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "page-home": LocalJSX.PageHome & JSXBase.HTMLAttributes<HTMLPageHomeElement>;
            "swipe-delete": LocalJSX.SwipeDelete & JSXBase.HTMLAttributes<HTMLSwipeDeleteElement>;
        }
    }
}
