/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface PageHome {
    }
    interface SlidingDrawer {
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLPageHomeElement extends Components.PageHome, HTMLStencilElement {
    }
    var HTMLPageHomeElement: {
        prototype: HTMLPageHomeElement;
        new (): HTMLPageHomeElement;
    };
    interface HTMLSlidingDrawerElement extends Components.SlidingDrawer, HTMLStencilElement {
    }
    var HTMLSlidingDrawerElement: {
        prototype: HTMLSlidingDrawerElement;
        new (): HTMLSlidingDrawerElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "page-home": HTMLPageHomeElement;
        "sliding-drawer": HTMLSlidingDrawerElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface PageHome {
    }
    interface SlidingDrawer {
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "page-home": PageHome;
        "sliding-drawer": SlidingDrawer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "page-home": LocalJSX.PageHome & JSXBase.HTMLAttributes<HTMLPageHomeElement>;
            "sliding-drawer": LocalJSX.SlidingDrawer & JSXBase.HTMLAttributes<HTMLSlidingDrawerElement>;
        }
    }
}
